name: Generate Snake

on:
  schedule:
    - cron: "0 0,12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: anadisharma1501
          outputs: |
            dist/github-snake.svg?color_snake=%2300f5ff&color_dots=%230d1117,%23003d5c,%23006080,%2300a3cc,%2300f5ff
            dist/github-snake-dark.svg?color_snake=%2300f5ff&color_dots=%230d1117,%23003d5c,%23006080,%2300a3cc,%2300f5ff
            dist/github-snake.gif?color_snake=%2300f5ff&color_dots=%230d1117,%23003d5c,%23006080,%2300a3cc,%2300f5ff

      - name: Push Snake to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
